/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateTaskInput {
  'title' : string,
  'tags' : Array<Tag>,
  'dueDate' : [] | [bigint],
  'description' : [] | [string],
  'priority' : Priority,
}
export type Priority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type Status = { 'Completed' : null } |
  { 'Pending' : null };
export type Tag = { 'Study' : null } |
  { 'Work' : null } |
  { 'Personal' : null };
export interface Task {
  'id' : string,
  'status' : Status,
  'title' : string,
  'order' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'tags' : Array<Tag>,
  'dueDate' : [] | [bigint],
  'description' : [] | [string],
  'updatedAt' : bigint,
  'priority' : Priority,
}
export interface TaskOrderEntry { 'id' : string, 'order' : bigint }
export interface UpdateTaskInput {
  'id' : string,
  'title' : string,
  'tags' : Array<Tag>,
  'dueDate' : [] | [bigint],
  'description' : [] | [string],
  'priority' : Priority,
}
export interface _SERVICE {
  'createTask' : ActorMethod<
    [CreateTaskInput],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'deleteTask' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'markComplete' : ActorMethod<[string], { 'ok' : Task } | { 'err' : string }>,
  'markIncomplete' : ActorMethod<
    [string],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'updateTask' : ActorMethod<
    [UpdateTaskInput],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'updateTaskOrder' : ActorMethod<
    [Array<TaskOrderEntry>],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];