/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tag = IDL.Variant({
  'Study' : IDL.Null,
  'Work' : IDL.Null,
  'Personal' : IDL.Null,
});
export const Priority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const CreateTaskInput = IDL.Record({
  'title' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});
export const Status = IDL.Variant({
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(Tag),
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'priority' : Priority,
});
export const UpdateTaskInput = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});
export const TaskOrderEntry = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func(
      [CreateTaskInput],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
  'deleteTask' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'markComplete' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
  'markIncomplete' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
  'updateTask' : IDL.Func(
      [UpdateTaskInput],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
  'updateTaskOrder' : IDL.Func(
      [IDL.Vec(TaskOrderEntry)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tag = IDL.Variant({
    'Study' : IDL.Null,
    'Work' : IDL.Null,
    'Personal' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const CreateTaskInput = IDL.Record({
    'title' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  const Status = IDL.Variant({ 'Completed' : IDL.Null, 'Pending' : IDL.Null });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(Tag),
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'priority' : Priority,
  });
  const UpdateTaskInput = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  const TaskOrderEntry = IDL.Record({ 'id' : IDL.Text, 'order' : IDL.Nat });
  
  return IDL.Service({
    'createTask' : IDL.Func(
        [CreateTaskInput],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
    'deleteTask' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'markComplete' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
    'markIncomplete' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
    'updateTask' : IDL.Func(
        [UpdateTaskInput],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
    'updateTaskOrder' : IDL.Func(
        [IDL.Vec(TaskOrderEntry)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };